// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.Data;

namespace MyCash.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyCash.API.Models.CategoriaConta", b =>
                {
                    b.Property<int>("CategoriaContaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaContaId");

                    b.ToTable("CategoriasContas");
                });

            modelBuilder.Entity("src.Models.Banco", b =>
                {
                    b.Property<int>("BancoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BancoId");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("src.Models.BandeiraCartao", b =>
                {
                    b.Property<int>("BandeiraCartaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BandeiraCartaoId");

                    b.ToTable("BandeirasCartoes");
                });

            modelBuilder.Entity("src.Models.CartaoCredito", b =>
                {
                    b.Property<int>("CartaoCreditoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BandeiraCartaoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LimiteCartao")
                        .HasColumnType("float");

                    b.HasKey("CartaoCreditoId");

                    b.HasIndex("BandeiraCartaoId");

                    b.ToTable("CartoesCredito");
                });

            modelBuilder.Entity("src.Models.CategoriaDespesa", b =>
                {
                    b.Property<int>("CategoriaDespesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubcategoriaDespesaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaDespesaId");

                    b.HasIndex("SubcategoriaDespesaId");

                    b.ToTable("CategoriasDespesas");
                });

            modelBuilder.Entity("src.Models.CategoriaReceita", b =>
                {
                    b.Property<int>("CategoriaReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubcategoriaReceitaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaReceitaId");

                    b.HasIndex("SubcategoriaReceitaId");

                    b.ToTable("CategoriasReceitas");
                });

            modelBuilder.Entity("src.Models.Conta", b =>
                {
                    b.Property<int>("ContaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BancoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaContaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SaldoAtual")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ContaId");

                    b.HasIndex("BancoId");

                    b.HasIndex("CategoriaContaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("src.Models.Despesa", b =>
                {
                    b.Property<int>("DespesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartaoCreditoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaDespesaId")
                        .HasColumnType("int");

                    b.Property<int>("ContaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDespesaCartaoCredito")
                        .HasColumnType("bit");

                    b.HasKey("DespesaId");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("CategoriaDespesaId");

                    b.HasIndex("ContaId");

                    b.HasIndex("FaturaId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("src.Models.Fatura", b =>
                {
                    b.Property<int>("FaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartaoCreditoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFechamentoFatura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimentoFatura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorFatura")
                        .HasColumnType("float");

                    b.Property<bool>("isFaturaPaga")
                        .HasColumnType("bit");

                    b.Property<bool>("isFaturaVencida")
                        .HasColumnType("bit");

                    b.HasKey("FaturaId");

                    b.HasIndex("CartaoCreditoId");

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("src.Models.Meta", b =>
                {
                    b.Property<int>("MetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaDespesaId")
                        .HasColumnType("int");

                    b.Property<double>("LimiteParaGastar")
                        .HasColumnType("float");

                    b.Property<double>("PercentualGasto")
                        .HasColumnType("float");

                    b.HasKey("MetaId");

                    b.HasIndex("CategoriaDespesaId");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("src.Models.Objetivo", b =>
                {
                    b.Property<int>("ObjetivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataFinal")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PercentualAcumulado")
                        .HasColumnType("float");

                    b.Property<double>("ValorAtual")
                        .HasColumnType("float");

                    b.Property<double>("ValorFinal")
                        .HasColumnType("float");

                    b.Property<double>("ValorMensal")
                        .HasColumnType("float");

                    b.HasKey("ObjetivoId");

                    b.ToTable("Objetivos");
                });

            modelBuilder.Entity("src.Models.Receita", b =>
                {
                    b.Property<int>("ReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaReceitaId")
                        .HasColumnType("int");

                    b.Property<int>("ContaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReceitaId");

                    b.HasIndex("CategoriaReceitaId");

                    b.HasIndex("ContaId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("src.Models.SubcategoriaDespesa", b =>
                {
                    b.Property<int>("SubcategoriaDespesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubcategoriaDespesaId");

                    b.ToTable("SubcategoriasDespesas");
                });

            modelBuilder.Entity("src.Models.SubcategoriaReceita", b =>
                {
                    b.Property<int>("SubcategoriaReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubcategoriaReceitaId");

                    b.ToTable("SubcategoriasReceitas");
                });

            modelBuilder.Entity("src.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("src.Models.CartaoCredito", b =>
                {
                    b.HasOne("src.Models.BandeiraCartao", "BandeiraCartao")
                        .WithMany()
                        .HasForeignKey("BandeiraCartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BandeiraCartao");
                });

            modelBuilder.Entity("src.Models.CategoriaDespesa", b =>
                {
                    b.HasOne("src.Models.SubcategoriaDespesa", "SubcategoriaDespesa")
                        .WithMany()
                        .HasForeignKey("SubcategoriaDespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubcategoriaDespesa");
                });

            modelBuilder.Entity("src.Models.CategoriaReceita", b =>
                {
                    b.HasOne("src.Models.SubcategoriaReceita", "SubcatecoriaReceita")
                        .WithMany()
                        .HasForeignKey("SubcategoriaReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubcatecoriaReceita");
                });

            modelBuilder.Entity("src.Models.Conta", b =>
                {
                    b.HasOne("src.Models.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCash.API.Models.CategoriaConta", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.Usuario", "Usuario")
                        .WithMany("Contas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("src.Models.Despesa", b =>
                {
                    b.HasOne("src.Models.CartaoCredito", "CartaoCredito")
                        .WithMany()
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CategoriaDespesa", "CategoriaDespesa")
                        .WithMany()
                        .HasForeignKey("CategoriaDespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.Fatura", null)
                        .WithMany("Despesas")
                        .HasForeignKey("FaturaId");

                    b.Navigation("CartaoCredito");

                    b.Navigation("CategoriaDespesa");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("src.Models.Fatura", b =>
                {
                    b.HasOne("src.Models.CartaoCredito", "CartaoCredito")
                        .WithMany()
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoCredito");
                });

            modelBuilder.Entity("src.Models.Meta", b =>
                {
                    b.HasOne("src.Models.CategoriaDespesa", "CategoriaDespesa")
                        .WithMany()
                        .HasForeignKey("CategoriaDespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaDespesa");
                });

            modelBuilder.Entity("src.Models.Receita", b =>
                {
                    b.HasOne("src.Models.CategoriaReceita", "CategoriaReceita")
                        .WithMany()
                        .HasForeignKey("CategoriaReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaReceita");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("src.Models.Fatura", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("src.Models.Usuario", b =>
                {
                    b.Navigation("Contas");
                });
#pragma warning restore 612, 618
        }
    }
}
